### PR TITLE
KS_83 #comment Drawer application option

### PR DESCRIPTION
**Pull request by EricKinyua**

### CODE REVIEW

**Review by CarltonK — CHANGES_REQUESTED** [review]
@EricKinyua Can you test with the Drawer on home_screen. Will it affect having a bottom bar?

**Comment by EricKinyua** [comment]
I don't think it will... Let me try and do that

**Comment by CarltonK** [comment]
Did this work?

**Comment by EricKinyua** [comment]
> Did this work?

Nope...I tried introducing the drawer to the homepage...No error but its not visible

**Comment by EricKinyua** [comment]
> @EricKinyua Can you test with the Drawer on home_screen. Will it affect having a bottom bar?

I have  tested it...No error but the drawer is not visible

**Pull request closed without merging**
